### ISSUE TITLE
How to install ??

### ISSUE THREAD

**Issue by ilixn** [VanCoding/mca.js#1]
I'm certainly a noob in node.js, but i can't (or don't know) install this. It isn't available on npm, so i cloned it in my node_modules directory with git. Then i did a `npm install` in the mca.js directory (cloned) and i tested a little script. Now Node tells me:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/dev/nodejs/mca.js-test/node_modules/mca.js/node_modules/weakmap.js/index.js:1:74)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

Do you know why i have this error (and how to solve it) , or how to install mca.js in another way ?

Thanks

**Comment by VanCoding** [comment]
This library is old and I never truly tested it for something serious.
That said, you might be able to use it when you do `npm install weak`
